apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: ambulance-ufe
  namespace: wac-hospital
spec:
  imageRepositoryRef:
    name: ambulance-ufe # referuje ImageRepository z predchádzajúceho kroku
  filterTags:
      pattern: '^master-(?P<timestamp>[0-9]{8}\.[0-9]{4})$'
      extract: '$timestamp'
  policy:
    numerical:
      order: asc
