apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

images:
- name: tomdrg/ambulance-ufe
  newName: tomdrg/ambulance-ufe # {"$imagepolicy":  "wac-hospital:ambulance-ufe:name"}
  newTag: master # {"$imagepolicy": "wac-hospital:ambulance-ufe:tag"}