apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
images:
- name: tomdrg/ambulance-ufe
  newName: tomdrg/ambulance-ufe # {"$imagepolicy":  "wac-hospital:ambulance-ufe:name"}
  newTag: master-20260417.1833 # {"$imagepolicy": "wac-hospital:ambulance-ufe:tag"}
- name: tomdrg/ambulance-wl-webapi
  newName: tomdrg/ambulance-wl-webapi # {"$imagepolicy":  "wac-hospital:ambulance-webapi:name"}
  newTag: main.20260331.1312 # {"$imagepolicy": "wac-hospital:ambulance-webapi:tag"}
