apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
images:
- name: tomdrg/ambulance-ufe
  newName: tomdrg/ambulance-ufe # {"$imagepolicy":  "wac-hospital:ambulance-ufe:name"}
  newTag: master.20260310.1327 # {"$imagepolicy": "wac-hospital:ambulance-ufe:tag"}
