apiVersion: polyfea.github.io/v1alpha1
kind: WebComponent
metadata:
  name: xdrga-ambulance-ufe-content
spec:
  microFrontend: xdrga-ambulance-ufe
  element: xdrga-ambulance-wl-app
  attributes:
    - name: base-path
      value: /xdrga-ambulance-wl/
  displayRules:
    - allOf:
      - context-name: main-content
      - path: "^(\\.?/)?xdrga-ambulance-wl(/.*)?$"
